src/Entity/AdvancesPayments.php
<?php

namespace App\Entity;

use App\DBAL\Types\AdvancesPaymentsStatusesType;
use App\Repository\AdvancesPaymentsRepository;
use App\Trait\TimeStampTrait;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Fresh\DoctrineEnumBundle\Validator\Constraints\EnumType;
use IntlDateFormatter;
use Locale;

#[ORM\Entity(repositoryClass: AdvancesPaymentsRepository::class)]
#[ORM\HasLifecycleCallbacks]
class AdvancesPayments
{
    use TimeStampTrait;

    /**
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var Users|null
     */
    #[ORM\ManyToOne(inversedBy: 'advancesPayments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    /**
     * @var Stores|null
     */
    #[ORM\ManyToOne(inversedBy: 'advancesPayments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Stores $store = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\ManyToMany(targetEntity: Products::class, inversedBy: 'advancesPayments', cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private Collection|ArrayCollection $products;

    /**
     * @var string
     */
    #[ORM\Column(name: 'advancesPaymentsStatus', type: 'AdvancesPaymentsStatusesType', nullable: false)]
    #[EnumType(entity: AdvancesPaymentsStatusesType::class)]
    private string $status = AdvancesPaymentsStatusesType::STATE_PENDING;

    /**
     * @var float|null
     */
    #[ORM\Column(nullable: false)]
    private ?float $depositAmount = null;

    /**
     * @var AdvancesPaymentsMethods|null
     */
    #[ORM\ManyToOne(inversedBy: 'advancesPayments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?AdvancesPaymentsMethods $paymentsMethod = null;

    /**
     * @var DateTimeImmutable|null
     */
    #[ORM\Column(nullable: false)]
    private ?DateTimeImmutable $expiredAt = null;

    /**
     * @var Customers|null
     */
    #[ORM\ManyToOne(cascade: ['persist'], inversedBy: 'advancesPayments')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Customers $customer = null;

    /**
     * @var string|null
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comments = null;

    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
        $this->products = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        $dateFormatter = IntlDateFormatter::create(
            Locale::getDefault(),
            IntlDateFormatter::FULL,
            IntlDateFormatter::NONE,
            null,
            IntlDateFormatter::GREGORIAN,
        );

        return $this->getStore() . ' - (' . $this->getUser() . ') - '
            . $dateFormatter->format($this->getCreatedAt()->getTimestamp());
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Users|null
     */
    public function getUser(): ?Users
    {
        return $this->user;
    }

    /**
     * @param Users|null $user
     * @return $this
     */
    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Stores|null
     */
    public function getStore(): ?Stores
    {
        return $this->store;
    }

    /**
     * @param Stores|null $store
     * @return $this
     */
    public function setStore(?Stores $store): self
    {
        $this->store = $store;

        return $this;
    }

    /**
     * @return Collection<int, Products>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    /**
     * @param Products $product
     * @return $this
     */
    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
        }

        return $this;
    }

    /**
     * @param Products $product
     * @return $this
     */
    public function removeProduct(Products $product): self
    {
        $this->products->removeElement($product);

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return $this
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getDepositAmount(): ?float
    {
        return $this->depositAmount;
    }

    /**
     * @param float $depositAmount
     * @return $this
     */
    public function setDepositAmount(float $depositAmount): self
    {
        $this->depositAmount = $depositAmount;

        return $this;
    }

    /**
     * @return AdvancesPaymentsMethods|null
     */
    public function getPaymentsMethod(): ?AdvancesPaymentsMethods
    {
        return $this->paymentsMethod;
    }

    /**
     * @param AdvancesPaymentsMethods|null $paymentsMethod
     * @return $this
     */
    public function setPaymentsMethod(?AdvancesPaymentsMethods $paymentsMethod): self
    {
        $this->paymentsMethod = $paymentsMethod;

        return $this;
    }

    /**
     * @return DateTimeImmutable|null
     */
    public function getExpiredAt(): ?DateTimeImmutable
    {
        return $this->expiredAt;
    }

    /**
     * @param DateTimeImmutable $expiredAt
     * @return $this
     */
    public function setExpiredAt(DateTimeImmutable $expiredAt): self
    {
        $this->expiredAt = $expiredAt;

        return $this;
    }

    /**
     * @return Customers|null
     */
    public function getCustomer(): ?Customers
    {
        return $this->customer;
    }

    /**
     * @param Customers|null $customer
     * @return $this
     */
    public function setCustomer(?Customers $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getComments(): ?string
    {
        return $this->comments;
    }

    /**
     * @param string|null $comments
     * @return $this
     */
    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use App\Trait\ContactTrait;
use App\Trait\TimeStampTrait;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[UniqueEntity('username')]
#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    use ContactTrait;
    use TimeStampTrait;

    /**
     * @var int|null
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 50, unique: true, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(min:2, max: 50)]
    private ?string $username = null;

    /**
     * @var UsersCivilities|null
     */
    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?UsersCivilities $civility = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Length(max: 50)]
    private ?string $firstname = null;

    /**
     * @var string|null
     */
    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Length(max: 50)]
    private ?string $lastname = null;

    /**
     * @var UsersPermissions|null
     */
    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull]
    private ?UsersPermissions $permission = null;

    /**
     * The hashed password
     * @var string|null The hashed password
     */
    #[ORM\Column(length: 255, nullable: false)]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $password = null;

    /**
     * The plain password
     * @var string|null
     */
    private ?string $plainPassword = null;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\ManyToMany(targetEntity: Stores::class, inversedBy: 'users')]
    private Collection|ArrayCollection $stores;

    /**
     * @var DateTimeInterface|null
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $birthdayDate = null;

    /**
     * @var DateTimeInterface|null
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $hiringDate = null;

    /**
     * @var bool|null
     */
    #[ORM\Column(nullable: false)]
    private ?bool $active = true;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Controls::class)]
    private Collection|ArrayCollection $controls;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: SafesMovements::class)]
    private Collection|ArrayCollection $safesMovements;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: SafesControls::class)]
    private Collection|ArrayCollection $safesControls;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Buybacks::class)]
    private Collection|ArrayCollection $buybacks;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: DepositsSales::class)]
    private Collection|ArrayCollection $depositsSales;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: AdvancesPayments::class)]
    private Collection|ArrayCollection $advancesPayments;

    /**
     * @var ArrayCollection|Collection
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Invoices::class)]
    private Collection|ArrayCollection $invoices;

    public function __construct()
    {
        $this->stores = new ArrayCollection();
        $this->controls = new ArrayCollection();
        $this->safesMovements = new ArrayCollection();
        $this->safesControls = new ArrayCollection();
        $this->buybacks = new ArrayCollection();
        $this->depositsSales = new ArrayCollection();
        $this->advancesPayments = new ArrayCollection();
        $this->invoices = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->getUsername();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->username ? ucfirst($this->username) : null;
    }

    /**
     * @param string $username
     * @return $this
     */
    public function setUsername(string $username): self
    {
        $this->username = strtolower($username);

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     * @see UserInterface
     * @return string
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @return UsersCivilities|null
     */
    public function getCivility(): ?UsersCivilities
    {
        return $this->civility;
    }

    /**
     * @param UsersCivilities|null $civility
     * @return $this
     */
    public function setCivility(?UsersCivilities $civility): self
    {
        $this->civility = $civility;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFirstname(): ?string
    {
        return $this->firstname ? ucfirst($this->firstname) : null;
    }

    /**
     * @param string|null $firstname
     * @return $this
     */
    public function setFirstname(?string $firstname): self
    {
        $this->firstname = strtolower($firstname);

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastname(): ?string
    {
        return $this->lastname ? strtoupper($this->lastname) : null;
    }

    /**
     * @param string|null $lastname
     * @return $this
     */
    public function setLastname(?string $lastname): self
    {
        $this->lastname = strtolower($lastname);

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFullname(): ?string
    {
        return (trim($this->getCivility() . ' ' . $this->getFirstname() . ' ' . $this->getLastName())) ?: null;
    }

    /**
     * @return UsersPermissions|null
     */
    public function getPermission(): ?UsersPermissions
    {
        return $this->permission;
    }

    /**
     * @param UsersPermissions|null $permission
     * @return $this
     */
    public function setPermission(?UsersPermissions $permission): self
    {
        $this->permission = $permission;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return [
            $this->permission->getRole()
        ];
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     * @return string
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @param string $password
     * @return $this
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    /**
     * @param string|null $plainPassword
     * @return $this
     */
    public function setPlainPassword(?string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @see UserInterface
     * @return void
     */
    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Stores>
     */
    public function getStores(): Collection
    {
        return $this->stores;
    }

    /**
     * @param Stores $store
     * @return $this
     */
    public function addStore(Stores $store): self
    {
        if (!$this->stores->contains($store)) {
            $this->stores->add($store);
        }

        return $this;
    }

    /**
     * @param Stores $store
     * @return $this
     */
    public function removeStore(Stores $store): self
    {
        $this->stores->removeElement($store);

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getBirthdayDate(): ?DateTimeInterface
    {
        return $this->birthdayDate;
    }

    /**
     * @param DateTimeInterface|null $birthdayDate
     * @return $this
     */
    public function setBirthdayDate(?DateTimeInterface $birthdayDate): self
    {
        $this->birthdayDate = $birthdayDate;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getHiringDate(): ?DateTimeInterface
    {
        return $this->hiringDate;
    }

    /**
     * @param DateTimeInterface|null $hiringDate
     * @return $this
     */
    public function setHiringDate(?DateTimeInterface $hiringDate): self
    {
        $this->hiringDate = $hiringDate;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function isActive(): ?bool
    {
        return $this->active;
    }

    /**
     * @param bool $active
     * @return $this
     */
    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return Collection<int, Controls>
     */
    public function getControls(): Collection
    {
        return $this->controls;
    }

    /**

templates/pdf/advances-payments/document-fr.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
    <head>
        <meta charset="utf-8">
        {% if links is defined %}
            {{ links }}
        {% endif %}
    </head>
    <body id="pdf-body">
        <header id="pdf-header">
            <section class="text-center">
                <img src="{{ absolute_url('/build/images/logo-dark.png') }}" alt="logo"><br>
                <h4 class="fw-bolder mt-2">
                    {{ advance_payments.store.city | upper }}
                </h4>
            </section>
        </header>
        <footer id="pdf-footer">
            <table class="w-100">
                <tbody>
                    <tr>
                        <td>
                            {% if advance_payments.store.phone is not empty %}
                                Téléphone : {{ advance_payments.store.phone | phone_number_format('NATIONAL') }}
                            {% endif %}
                        </td>
                        <td class="text-end">
                            {% if advance_payments.store.email is not empty %}
                                Email : {{ advance_payments.store.email }}
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>
            <article class="text-center">
                <small>
                    {% if advance_payments.store.commercialRegisterNumber is not empty %}
                        RCS {{ advance_payments.store.commercialRegisterNumber }}
                    {% endif %}
                </small>
            </article>
        </footer>
        <main>
            <article class="copy-for text-end text-decoration-underline float-end">
                {{ copy_for }}
            </article>
            <h3 class="text-center mb-5">
                ACOMPTE NON-REMBOURSABLE
            </h3>
            <table class="table table-between mb-5">
                <tbody>
                    <tr>
                        <td>
                            « Le client » :<br>
                            {%  if advance_payments.customer.civility is defined and advance_payments.customer.firstname is defined and advance_payments.customer.lastname is defined %}
                                {{ advance_payments.customer.civility ~ ' ' ~ advance_payments.customer.firstname ~ ' ' ~ advance_payments.customer.lastname }}<br>
                            {% endif %}
                            {%  if advance_payments.customer.address is defined and advance_payments.customer.address is not empty %}
                                {{ advance_payments.customer.address }}<br>
                            {% endif %}
                            {%  if advance_payments.customer.additionalAddress is defined and advance_payments.customer.additionalAddress is not empty %}
                                {{ advance_payments.customer.additionalAddress }}<br>
                            {% endif %}
                            {%  if advance_payments.customer.zipcode is defined or advance_payments.customer.city is defined %}
                                {{ advance_payments.customer.zipcode }} {{ advance_payments.customer.city }}<br>
                            {% endif %}
                            {%  if advance_payments.customer.idNumber is defined %}
                                Pièce d'identitée n°: {{ advance_payments.customer.idNumber }}
                            {% endif %}
                        </td>
                        <td>
                            « Le magasin » :<br>
                            AXE CASH {{ advance_payments.store.city | upper }}<br>
                            {% if advance_payments.store.address is not empty %}
                                {{ advance_payments.store.address }}<br>
                            {% endif %}
                            {% if advance_payments.store.additionalAddress is not empty %}
                                {{ advance_payments.store.additionalAddress }}<br>
                            {% endif %}
                            {{ advance_payments.store.zipcode }} {{ advance_payments.store.city | upper }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <p class="mb-4">
                « Le magasin » déclare avoir reçu ce jour, de la part « du client » un acompte non-remboursable pour les bien ci-après :
            </p>
            <table class="table table-bordered mb-4">
                <thead>
                    <tr>
                        <th>
                            Code barre
                        </th>
                        <th>
                            Produit
                        </th>
                        <th>
                            Numéro de série
                        </th>
                        <th>
                            Prix H.T.
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in advance_payments.products %}
                        <tr>
                            <td>
                                {{ product.barCode }}
                            </td>
                            <td>
                                {{ product.label }}
                            </td>
                            <td>
                                {{ product.serialNumber }}
                            </td>
                            <td>
                                {{ (product.price / 100) | round(2, 'common') | replace({'.' : ','}) }} euros
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p>
                « Le client » verse « au magasin » un acompte d'un montant de
                <span class="fw-bold">
                    {{ (advance_payments.depositAmount / 100) | round(2, 'common') | replace({'.' : ','}) }}
                </span>
                euros en
                <span class="fw-bold">
                    {{ advance_payments.paymentsMethod | lower }}
                </span>
                .
            </p>
            <p>
                « Le client » s'engage a versé le solde de son achat auprès « du magasin » avant le
                <span class="fw-bold">
                    {{ advance_payments.expiredAt | date("d/m/Y", false) }}.
                </span>
            </p>
            <p>
                « Le magasin » remettra « au client » les produits le jour du paiement du solde.
            </p>
            <p>
                Passé la date limite de paiement, l'acompte ne sera pas remboursé et les produits remis à la vente.<br>
            </p>
            <p>
                Le versement du solde et la récupération des produits devront être exercée selon la modalité suivante :<br>
                - « Le client » se présentera, durant les heures normales d’ouverture « du magasin », personnellement, dans « le magasin » où il a versé l'acompte, muni d’une pièce d’identité en cours de validité et de l’original de l’exemplaire qui lui a été remis du présent contrat.
            </p>
            <p class="mb-5">
                Tout litige relatif au contrat relèvera, à défaut d’accord amiable, de la compétence exclusive du Tribunal de Commerce de Cannes.
            </p>
            <p>
                Fait en 2 exemplaires le
                <span class="fw-bold">
                    {{ advance_payments.createdAt | date("d/m/Y", false) }}
                </span>
            </p>
            <table class="table table-between">
                <tbody>
                    <tr>
                        <td>
                            « Le client » :<br>
                            {%  if advance_payments.customer.civility is defined and advance_payments.customer.firstname is defined and advance_payments.customer.lastname is defined %}
                                {{ advance_payments.customer.civility ~ ' ' ~ advance_payments.customer.firstname ~ ' ' ~ advance_payments.customer.lastname }}<br>
                            {% endif %}
                            Lu et approuvé – Bon pour accord
                        </td>
                        <td>
                            « Le magasin » :<br>
                            AXE CASH {{ advance_payments.store.city | upper }}<br>
                            ({{ advance_payments.user.fullname }})
                        </td>
                    </tr>
                </tbody>
            </table>
        </main>
    </body>
</html>